### PR TITLE
Support for XDG Base Directory

### PR DESCRIPTION
**Pull request by Jonassenher**
Today's mutt-wizard does not support the XDG Base Directory specifications (https://wiki.archlinux.org/index.php/XDG_Base_Directory) because they say the user should be able to change the config, cache, data folders etc. using the environmental variables XDG_CONFIG_HOME, XDG_CACHE_HOME, and XDG_DATA_HOME; instead MW hard codes the default paths ~/.config, ~/.cache, and ~/.local/share. My commit corrects this.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
As it is, this will break the msmtp and mbsync config files for people who do not have the environmental variables assigned.

**Comment by Jonassenher** [comment]
If you looked at the actual changes I made, I'm pretty sure I made it so that it always defaults back to the original folder if the environmental variables are not assigned?

All of my lines are of the type
```
cachedir="${XDG_CACHE_HOME:-$HOME/.cache}/mutt-wizard"
```
So if `XDG_CACHE_HOME` is not set, then `cachedir` will be set to `$HOME/.cache/mutt-wizard` as always.

Or am I missing something?

**Comment by LukeSmithxyz** [comment]
Lines 41, 62 and 63 are the issue. Actually test it if you doubt.

**Comment by LukeSmithxyz** [comment]
Actually, come to think of it, since you're inventing some new variable for a mbsyncrc file, you might as well *actually have mbsync use it* when it's called in the script. Otherwise it's just going to break everything.

**Comment by Jonassenher** [comment]
OK, I'm sorry, you are right. Is my last commit better?

I'll look into having mbsync using it as well.

**Comment by Jonassenher** [comment]
I'm pretty I have fixed everything now, at least it works fine on my computer with the changes I made.

**Pull request merged**
