### PR TITLE
fixed mailbox.org smtp server

### PR DESCRIPTION
**Pull request by tim241**
so I tried to use mailbox.org but upon sending a mail, it was stuck on `connecting to smtp...` I applied this patch and it fixed it :+1:

### CODE REVIEW

**Comment by tim241** [comment]
thank you! :smile:

**Comment by Astronach** [comment]
Are you sure with this? For me it only works the old way with "smtp.mailbox.org"
see: [here](https://kb.mailbox.org/display/MBOKB/E-Mail-Einrichtung+-+allgemein)

**Comment by elagost** [comment]
Configuring my own account, needed to add `tls_starttls=on` in the upper section, and mailbox.org needs to use `smtp.mailbox.org` and port 587 now.

**Comment by elagost** [comment]
[Created the pull request for this change](https://github.com/LukeSmithxyz/mutt-wizard/pull/187)

**Comment by mbbogh** [comment]
Please don't accept this pull request. It opens the possibility for a **STRIPTLS attack**.
@Astronach is right. The pre @tim241 configuration `smtp.mailbox.org` and `465` is still on the mailbox.org knowledge base page from 2019-04-17.

**Pull request merged**
