### PR TITLE
allow dynamically loading available mailboxes

### PR DESCRIPTION
**Pull request by epsilon-0**
this way if a folder is added or deleted in the remote
location, and gets deleted after sync, it is reflected
in the next opening

Signed-off-by: Aisha Tammy <floss@bsd.ac>

---

adapted and modified version of https://neomutt.org/guide/advancedusage.html#note-11

### CODE REVIEW

**Comment by PRESFIL** [comment]
Very interesting! We have already dealt with other users in this direction some time ago (#619, #620).

As far as I remember, we had a problem finding intermediate folders (cur | new | tmp)  ([see](https://github.com/LukeSmithxyz/mutt-wizard/issues/619#issuecomment-763134018)). Then I solved it by expanding the search, removing duplicates and using a complex conditional loop in sed. Your solution looks like you already solved this problem.

Also, you immediately substituted a variable with a mailbox path there, which is cool! :brain:

**Comment by PRESFIL** [comment]
I took a closer look, and now I don't think the problem is solved. :smile: It will be triggered on the cur mailbox, and it will be ignored (as it seems to me). In any case, you can improve my version by adding a variable statement there.

**Comment by epsilon-0** [comment]
Sorry could you give me a directory hierarchy example where this would fail?
That would make it easier to understand.

**Comment by epsilon-0** [comment]
OK, I've updated it to also handle this case.

**Comment by PRESFIL** [comment]
In general, it may have been paranoia. I have not been able to reproduce such a situation. Here's what I've tried.

<details>
<summary>...</summary>

```sh
tree /tmp/mailbox
```

```
/tmp/mailbox/
├── cur
│   ├── cur
│   ├── new
│   └── tmp
├── Drafts
│   ├── cur
│   ├── new
│   ├── templates
│   │   ├── cur
│   │   ├── new
│   │   └── tmp
│   └── tmp
├── INBOX
│   ├── cur
│   │   ├── cur
│   │   ├── new
│   │   │   ├── cur
│   │   │   ├── new
│   │   │   └── tmp
│   │   └── tmp
│   ├── new
│   └── tmp
├── new
└── tmp

24 directories, 0 files

```

```sh
mdir=/tmp/mailbox/
```

1 variant:

```sh
find $mdir -type d -name cur | sort | sed -e 's:/cur/*$::' -e "s:$mdir:=:" -e 's:^:":' -e 's:$:":' | tr '\n' ' '
```

```
"/tmp/mailbox" "=cur" "=Drafts" "=Drafts/templates" "=INBOX" "=INBOX/cur" "=INBOX/cur/new"
```

2 variant:

```sh
find $mdir -type d -name cur | sort | sed -e 's:/cur$:":' -e "s:$mdir:\"=:" | tr '\n' ' '
```

```
/tmp/mailbox" "=cur" "=Drafts" "=Drafts/templates" "=INBOX" "=INBOX/cur" "=INBOX/cur/new"
```

</details>

Both work the same, **except that the second one loses one quote at the beginning**, because it doesn't have a `/` at the end, but it does in the `$mdir` variable.

```sh
echo $mdir
/tmp/mailbox/
```

p.s. Please, don't force push this branch

**Comment by epsilon-0** [comment]
The top level Maildir folder can't be a mail folder and have a `cur`. Is this handling for some different cases?

> p.s. Please, don't force push this branch

Gotcha.

**Comment by PRESFIL** [comment]
> Both work the same, except that the second one loses one quote at the beginning, because it doesn't have a / at the end, but it does in the $mdir variable.

But this error still remains. See the examples.

**Comment by epsilon-0** [comment]
I've updated it to use `-mindepth 1`. Does it look better now?

**Comment by PRESFIL** [comment]
Oh, yes, it's better now. I didn't realize then that `/tmp/mailbox` shouldn't be a mailbox. You solved 2 problems at a time.

I do not see any problems.

**Comment by epsilon-0** [comment]
Is there anything holding this back still?
Lemme know if I should make any more changes.

**Comment by PRESFIL** [comment]
I don't see any problems. The only question is, will it interfere with POP accounts?
I don’t use it and therefore I don’t know.

**Comment by PRESFIL** [comment]
Congrats! :tada:

**Pull request merged**
