### PR TITLE
notification of new mail in all folders

### PR DESCRIPTION
**Pull request by rjl6789**
sometimes new mail is not necessarily in the inbox e.g. if mail server applies filters.  This commit lists all folders and works through each one giving a notification of mail for each folder (using the existing code).  It also creates a couple of global variables for the mail directory and .mailsynclastrun file.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
Well I mean the point of specifically checking the inbox is to exclude directories like send, drafts, junk, trash, etc.

Wouldn't this give you a notification if you saved a draft remotely?

**Comment by rjl6789** [comment]
agreed. bugger. hadn't thought that one through. Sorry! Please reject.

**Comment by rjl6789** [comment]
(could probably work if excluded sent / drafts / junk trash) but gets (even) messier then)

**Comment by rjl6789** [comment]
exclude drafts, sent, trash etc from search for new mail.  I still believe it's useful to have a notification for all the folders except these, actually I don't think it's that messy either.  Having said that... if you disagree no worries.

**Comment by rjl6789** [comment]
sorry for the spam.  Changed my mind (again). this just matches patterns.  If had a bolder called "binary" this would be excluded as well.

**Pull request closed without merging**
