### PR TITLE
Automatic determining of IMAP hierarchy delimiter

### PR DESCRIPTION
**Pull request by PRESFIL**
First try to implement #600. I used `curl` for this. It is optional currently, so, if the user doesn't want to, he can choose not to install it, though, IMHO, `curl` there is everywhere where you come.

Also, determined delimiter inserts into *mutt account*, so, it renders as before this changes.

`\` and `/` ignored, as `mbsync` does. In that case default `.` will be used.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
I'm probably going to this done in one fell swoop of curl by using it for login as well.

**Comment by PRESFIL** [comment]
I also thought about it, I think this PR can be easily redone, if you decide. I activated the "Allow edits by maintainers" feature.

**Comment by LukeSmithxyz** [comment]
I'm looking at what you have and I'm a little confused. You have `.` as the default value for `Flatten` and `.` if the server has `/` or `\` as delimiters, but if someone has some other character like `|`, then that character is set to `Flatten`?

I mean I think the actual issue here is people having `.` in their mailbox names, in which case we should really be testing for that and if they do, choosing some other character unused in the names to flatten to.

You know, I don't actually remember why I originally had to include `Flatten`. I don't use an email address with hierarchical mailboxes, but I think there's a chance we might be able to survive without it. I feel like I originally implemented it because I had some much more clumsy way of determining mailboxes.

**Comment by PRESFIL** [comment]
> I'm looking at what you have and I'm a little confused. You have `.` as the default value for `Flatten` and `.` if the server has `/` or `\` as delimiters, but if someone has some other character like `|`, then that character is set to `Flatten`?

Yes, I [think](https://github.com/LukeSmithxyz/mutt-wizard/issues/546#issuecomment-752423567) that if you use the separator that is used on the server side, you can reduce the chance of conflict. In addition, this separator will necessarily be 7-bit ASCII, which will allow you to work on any UNIX file system (`mutt`/`neomutt` + `mbsync` is not going to be ported to Windows?). But sometimes they are chosen very [well](https://github.com/LukeSmithxyz/mutt-wizard/issues/546#issuecomment-752431994).

> You know, I don't actually remember why I originally had to include `Flatten`.

It seems to me that you chose such a `Flatten .` because it is written in `mbsync(1)`.

> I don't use an email address with hierarchical mailboxes, but I think there's a chance we might be able to survive without it. I feel like I originally implemented it because I had some much more clumsy way of determining mailboxes.

Still, some users/vendors have them. Do not redo the user's archive if `mbsync` supports the hierarchy. At the very least, you can try to minimize incompatibilities. But I'm also against a lot of spaghetti to define it.

It would be better if the separator was hard-defined in the standard... :anger:

**Pull request closed without merging**
