### PR TITLE
fix: the content from 'From' seems a bit mess

### PR DESCRIPTION
**Pull request by Shane-XB-Qian**
// solution: just get whole content from/after 'From:' one line

### CODE REVIEW

**Comment by Shane-XB-Qian** [comment]
what happened? why you just closed it..
// i verified at my local, seems this is an acceptable solution.

**Comment by LukeSmithxyz** [comment]
Well it isn't because it literally just undid the decoding I restored in the last commit.

**Comment by Shane-XB-Qian** [comment]
your last commit for 'subject' seems good, but just the 'from' was not very correct which made irrelevant chars included in 'from' too, so i just simplify the content just from '^From: ' i thought it should be good enough.

**Comment by LukeSmithxyz** [comment]
🤦

**Pull request closed without merging**
